version: '3'

tasks:
  dev:
    env:
      CONFIG_PATH: ./config/local.yml
    cmds:
      - go run ./cmd/chatapi/main.go

  run:
    env:
      CONFIG_PATH: ./config/local.yml
    cmds:
      - ./build/chatapi/main

  build:
    cmds:
      - go build -v -o ./build/chatapi/main ./cmd/chatapi/main.go
         
  docker-build:
    cmds:
      - docker build -t chat:latest -f ./build/docker/Dockerfile .

  docker-up:
    cmds:
      - docker-compose -f ./build/docker/docker-compose.yml up -d

  docker-down:
    cmds:
      - docker-compose -f ./build/docker/docker-compose.yml down

  migration-main:
    env:
      CONFIG_PATH: ./config/local.yml
    cmds:
      - "go run ./cmd/migrator \
      --migration-path=./migrations/ \
      --migrations-table=migrations"
    